#!/bin/sh

# trailing slash will copy files from inside rather than src itself
BACKUP_SRC="${BACKUP_SRC:-$HOME/backup/}"

if [ -z "$BACKUP_DEST" ]; then
	printf 'Set BACKUP_DEST env var ' >&2
	printf 'e.g. user@host:backup in ~/.bash_profile\n' >&2
	exit 1
fi

set -x
rsync -vhrtu --progress "$@" "$BACKUP_SRC" "$BACKUP_DEST"
